/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransactionsIndexRouteImport } from './routes/api/transactions/index'
import { Route as ApiRecurringTransactionsIndexRouteImport } from './routes/api/recurring-transactions/index'
import { Route as ApiConnectionsIndexRouteImport } from './routes/api/connections/index'
import { Route as ApiCategoriesIndexRouteImport } from './routes/api/categories/index'
import { Route as ApiCashflowIndexRouteImport } from './routes/api/cashflow/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiTransactionsYearsRangeRouteImport } from './routes/api/transactions/years-range'
import { Route as ApiTransactionsIdRouteImport } from './routes/api/transactions/$id'
import { Route as ApiRecurringTransactionsIdRouteImport } from './routes/api/recurring-transactions/$id'
import { Route as ApiConnectionsIdRouteImport } from './routes/api/connections/$id'
import { Route as ApiConnectionsRequestsIndexRouteImport } from './routes/api/connections/requests/index'
import { Route as ApiRecurringTransactionsIdToggleRouteImport } from './routes/api/recurring-transactions/$id/toggle'
import { Route as AuthedDashboardTransactionsLayoutRouteImport } from './routes/_authed/dashboard/transactions/_layout'
import { Route as AuthedDashboardConnectionsLayoutRouteImport } from './routes/_authed/dashboard/connections/_layout'
import { Route as AuthedDashboardTransactionsLayoutIndexRouteImport } from './routes/_authed/dashboard/transactions/_layout.index'
import { Route as AuthedDashboardConnectionsLayoutIndexRouteImport } from './routes/_authed/dashboard/connections/_layout.index'
import { Route as AuthedDashboardTransactionsNewLayoutRouteImport } from './routes/_authed/dashboard/transactions/new/_layout'
import { Route as AuthedDashboardTransactionsTransactionIdLayoutRouteImport } from './routes/_authed/dashboard/transactions/$transactionId/_layout'
import { Route as AuthedDashboardTransactionsNewLayoutIndexRouteImport } from './routes/_authed/dashboard/transactions/new/_layout.index'
import { Route as AuthedDashboardTransactionsTransactionIdLayoutIndexRouteImport } from './routes/_authed/dashboard/transactions/$transactionId/_layout.index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsIndexRoute = ApiTransactionsIndexRouteImport.update({
  id: '/api/transactions/',
  path: '/api/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecurringTransactionsIndexRoute =
  ApiRecurringTransactionsIndexRouteImport.update({
    id: '/api/recurring-transactions/',
    path: '/api/recurring-transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectionsIndexRoute = ApiConnectionsIndexRouteImport.update({
  id: '/api/connections/',
  path: '/api/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIndexRoute = ApiCategoriesIndexRouteImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCashflowIndexRoute = ApiCashflowIndexRouteImport.update({
  id: '/api/cashflow/',
  path: '/api/cashflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTransactionsYearsRangeRoute =
  ApiTransactionsYearsRangeRouteImport.update({
    id: '/api/transactions/years-range',
    path: '/api/transactions/years-range',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransactionsIdRoute = ApiTransactionsIdRouteImport.update({
  id: '/api/transactions/$id',
  path: '/api/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecurringTransactionsIdRoute =
  ApiRecurringTransactionsIdRouteImport.update({
    id: '/api/recurring-transactions/$id',
    path: '/api/recurring-transactions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectionsIdRoute = ApiConnectionsIdRouteImport.update({
  id: '/api/connections/$id',
  path: '/api/connections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRequestsIndexRoute =
  ApiConnectionsRequestsIndexRouteImport.update({
    id: '/api/connections/requests/',
    path: '/api/connections/requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecurringTransactionsIdToggleRoute =
  ApiRecurringTransactionsIdToggleRouteImport.update({
    id: '/toggle',
    path: '/toggle',
    getParentRoute: () => ApiRecurringTransactionsIdRoute,
  } as any)
const AuthedDashboardTransactionsLayoutRoute =
  AuthedDashboardTransactionsLayoutRouteImport.update({
    id: '/dashboard/transactions/_layout',
    path: '/dashboard/transactions',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardConnectionsLayoutRoute =
  AuthedDashboardConnectionsLayoutRouteImport.update({
    id: '/dashboard/connections/_layout',
    path: '/dashboard/connections',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardTransactionsLayoutIndexRoute =
  AuthedDashboardTransactionsLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardTransactionsLayoutRoute,
  } as any)
const AuthedDashboardConnectionsLayoutIndexRoute =
  AuthedDashboardConnectionsLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardConnectionsLayoutRoute,
  } as any)
const AuthedDashboardTransactionsNewLayoutRoute =
  AuthedDashboardTransactionsNewLayoutRouteImport.update({
    id: '/dashboard/transactions/new/_layout',
    path: '/dashboard/transactions/new',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardTransactionsTransactionIdLayoutRoute =
  AuthedDashboardTransactionsTransactionIdLayoutRouteImport.update({
    id: '/dashboard/transactions/$transactionId/_layout',
    path: '/dashboard/transactions/$transactionId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardTransactionsNewLayoutIndexRoute =
  AuthedDashboardTransactionsNewLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardTransactionsNewLayoutRoute,
  } as any)
const AuthedDashboardTransactionsTransactionIdLayoutIndexRoute =
  AuthedDashboardTransactionsTransactionIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardTransactionsTransactionIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/connections/$id': typeof ApiConnectionsIdRoute
  '/api/recurring-transactions/$id': typeof ApiRecurringTransactionsIdRouteWithChildren
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/transactions/years-range': typeof ApiTransactionsYearsRangeRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/api/cashflow/': typeof ApiCashflowIndexRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/connections/': typeof ApiConnectionsIndexRoute
  '/api/recurring-transactions/': typeof ApiRecurringTransactionsIndexRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
  '/dashboard/connections': typeof AuthedDashboardConnectionsLayoutRouteWithChildren
  '/dashboard/transactions': typeof AuthedDashboardTransactionsLayoutRouteWithChildren
  '/api/recurring-transactions/$id/toggle': typeof ApiRecurringTransactionsIdToggleRoute
  '/api/connections/requests/': typeof ApiConnectionsRequestsIndexRoute
  '/dashboard/transactions/$transactionId': typeof AuthedDashboardTransactionsTransactionIdLayoutRouteWithChildren
  '/dashboard/transactions/new': typeof AuthedDashboardTransactionsNewLayoutRouteWithChildren
  '/dashboard/connections/': typeof AuthedDashboardConnectionsLayoutIndexRoute
  '/dashboard/transactions/': typeof AuthedDashboardTransactionsLayoutIndexRoute
  '/dashboard/transactions/$transactionId/': typeof AuthedDashboardTransactionsTransactionIdLayoutIndexRoute
  '/dashboard/transactions/new/': typeof AuthedDashboardTransactionsNewLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/connections/$id': typeof ApiConnectionsIdRoute
  '/api/recurring-transactions/$id': typeof ApiRecurringTransactionsIdRouteWithChildren
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/transactions/years-range': typeof ApiTransactionsYearsRangeRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/api/cashflow': typeof ApiCashflowIndexRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/connections': typeof ApiConnectionsIndexRoute
  '/api/recurring-transactions': typeof ApiRecurringTransactionsIndexRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
  '/api/recurring-transactions/$id/toggle': typeof ApiRecurringTransactionsIdToggleRoute
  '/api/connections/requests': typeof ApiConnectionsRequestsIndexRoute
  '/dashboard/connections': typeof AuthedDashboardConnectionsLayoutIndexRoute
  '/dashboard/transactions': typeof AuthedDashboardTransactionsLayoutIndexRoute
  '/dashboard/transactions/$transactionId': typeof AuthedDashboardTransactionsTransactionIdLayoutIndexRoute
  '/dashboard/transactions/new': typeof AuthedDashboardTransactionsNewLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/api/connections/$id': typeof ApiConnectionsIdRoute
  '/api/recurring-transactions/$id': typeof ApiRecurringTransactionsIdRouteWithChildren
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/transactions/years-range': typeof ApiTransactionsYearsRangeRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/api/cashflow/': typeof ApiCashflowIndexRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/connections/': typeof ApiConnectionsIndexRoute
  '/api/recurring-transactions/': typeof ApiRecurringTransactionsIndexRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
  '/_authed/dashboard/connections/_layout': typeof AuthedDashboardConnectionsLayoutRouteWithChildren
  '/_authed/dashboard/transactions/_layout': typeof AuthedDashboardTransactionsLayoutRouteWithChildren
  '/api/recurring-transactions/$id/toggle': typeof ApiRecurringTransactionsIdToggleRoute
  '/api/connections/requests/': typeof ApiConnectionsRequestsIndexRoute
  '/_authed/dashboard/transactions/$transactionId/_layout': typeof AuthedDashboardTransactionsTransactionIdLayoutRouteWithChildren
  '/_authed/dashboard/transactions/new/_layout': typeof AuthedDashboardTransactionsNewLayoutRouteWithChildren
  '/_authed/dashboard/connections/_layout/': typeof AuthedDashboardConnectionsLayoutIndexRoute
  '/_authed/dashboard/transactions/_layout/': typeof AuthedDashboardTransactionsLayoutIndexRoute
  '/_authed/dashboard/transactions/$transactionId/_layout/': typeof AuthedDashboardTransactionsTransactionIdLayoutIndexRoute
  '/_authed/dashboard/transactions/new/_layout/': typeof AuthedDashboardTransactionsNewLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/connections/$id'
    | '/api/recurring-transactions/$id'
    | '/api/transactions/$id'
    | '/api/transactions/years-range'
    | '/dashboard/'
    | '/api/cashflow/'
    | '/api/categories/'
    | '/api/connections/'
    | '/api/recurring-transactions/'
    | '/api/transactions/'
    | '/dashboard/connections'
    | '/dashboard/transactions'
    | '/api/recurring-transactions/$id/toggle'
    | '/api/connections/requests/'
    | '/dashboard/transactions/$transactionId'
    | '/dashboard/transactions/new'
    | '/dashboard/connections/'
    | '/dashboard/transactions/'
    | '/dashboard/transactions/$transactionId/'
    | '/dashboard/transactions/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/connections/$id'
    | '/api/recurring-transactions/$id'
    | '/api/transactions/$id'
    | '/api/transactions/years-range'
    | '/dashboard'
    | '/api/cashflow'
    | '/api/categories'
    | '/api/connections'
    | '/api/recurring-transactions'
    | '/api/transactions'
    | '/api/recurring-transactions/$id/toggle'
    | '/api/connections/requests'
    | '/dashboard/connections'
    | '/dashboard/transactions'
    | '/dashboard/transactions/$transactionId'
    | '/dashboard/transactions/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/api/connections/$id'
    | '/api/recurring-transactions/$id'
    | '/api/transactions/$id'
    | '/api/transactions/years-range'
    | '/_authed/dashboard/'
    | '/api/cashflow/'
    | '/api/categories/'
    | '/api/connections/'
    | '/api/recurring-transactions/'
    | '/api/transactions/'
    | '/_authed/dashboard/connections/_layout'
    | '/_authed/dashboard/transactions/_layout'
    | '/api/recurring-transactions/$id/toggle'
    | '/api/connections/requests/'
    | '/_authed/dashboard/transactions/$transactionId/_layout'
    | '/_authed/dashboard/transactions/new/_layout'
    | '/_authed/dashboard/connections/_layout/'
    | '/_authed/dashboard/transactions/_layout/'
    | '/_authed/dashboard/transactions/$transactionId/_layout/'
    | '/_authed/dashboard/transactions/new/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiConnectionsIdRoute: typeof ApiConnectionsIdRoute
  ApiRecurringTransactionsIdRoute: typeof ApiRecurringTransactionsIdRouteWithChildren
  ApiTransactionsIdRoute: typeof ApiTransactionsIdRoute
  ApiTransactionsYearsRangeRoute: typeof ApiTransactionsYearsRangeRoute
  ApiCashflowIndexRoute: typeof ApiCashflowIndexRoute
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiConnectionsIndexRoute: typeof ApiConnectionsIndexRoute
  ApiRecurringTransactionsIndexRoute: typeof ApiRecurringTransactionsIndexRoute
  ApiTransactionsIndexRoute: typeof ApiTransactionsIndexRoute
  ApiConnectionsRequestsIndexRoute: typeof ApiConnectionsRequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/': {
      id: '/api/transactions/'
      path: '/api/transactions'
      fullPath: '/api/transactions/'
      preLoaderRoute: typeof ApiTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring-transactions/': {
      id: '/api/recurring-transactions/'
      path: '/api/recurring-transactions'
      fullPath: '/api/recurring-transactions/'
      preLoaderRoute: typeof ApiRecurringTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/': {
      id: '/api/connections/'
      path: '/api/connections'
      fullPath: '/api/connections/'
      preLoaderRoute: typeof ApiConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories/'
      preLoaderRoute: typeof ApiCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cashflow/': {
      id: '/api/cashflow/'
      path: '/api/cashflow'
      fullPath: '/api/cashflow/'
      preLoaderRoute: typeof ApiCashflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/transactions/years-range': {
      id: '/api/transactions/years-range'
      path: '/api/transactions/years-range'
      fullPath: '/api/transactions/years-range'
      preLoaderRoute: typeof ApiTransactionsYearsRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/api/transactions/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring-transactions/$id': {
      id: '/api/recurring-transactions/$id'
      path: '/api/recurring-transactions/$id'
      fullPath: '/api/recurring-transactions/$id'
      preLoaderRoute: typeof ApiRecurringTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/$id': {
      id: '/api/connections/$id'
      path: '/api/connections/$id'
      fullPath: '/api/connections/$id'
      preLoaderRoute: typeof ApiConnectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections/requests/': {
      id: '/api/connections/requests/'
      path: '/api/connections/requests'
      fullPath: '/api/connections/requests/'
      preLoaderRoute: typeof ApiConnectionsRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring-transactions/$id/toggle': {
      id: '/api/recurring-transactions/$id/toggle'
      path: '/toggle'
      fullPath: '/api/recurring-transactions/$id/toggle'
      preLoaderRoute: typeof ApiRecurringTransactionsIdToggleRouteImport
      parentRoute: typeof ApiRecurringTransactionsIdRoute
    }
    '/_authed/dashboard/transactions/_layout': {
      id: '/_authed/dashboard/transactions/_layout'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthedDashboardTransactionsLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/connections/_layout': {
      id: '/_authed/dashboard/connections/_layout'
      path: '/dashboard/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof AuthedDashboardConnectionsLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/transactions/_layout/': {
      id: '/_authed/dashboard/transactions/_layout/'
      path: '/'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof AuthedDashboardTransactionsLayoutIndexRouteImport
      parentRoute: typeof AuthedDashboardTransactionsLayoutRoute
    }
    '/_authed/dashboard/connections/_layout/': {
      id: '/_authed/dashboard/connections/_layout/'
      path: '/'
      fullPath: '/dashboard/connections/'
      preLoaderRoute: typeof AuthedDashboardConnectionsLayoutIndexRouteImport
      parentRoute: typeof AuthedDashboardConnectionsLayoutRoute
    }
    '/_authed/dashboard/transactions/new/_layout': {
      id: '/_authed/dashboard/transactions/new/_layout'
      path: '/dashboard/transactions/new'
      fullPath: '/dashboard/transactions/new'
      preLoaderRoute: typeof AuthedDashboardTransactionsNewLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/transactions/$transactionId/_layout': {
      id: '/_authed/dashboard/transactions/$transactionId/_layout'
      path: '/dashboard/transactions/$transactionId'
      fullPath: '/dashboard/transactions/$transactionId'
      preLoaderRoute: typeof AuthedDashboardTransactionsTransactionIdLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/transactions/new/_layout/': {
      id: '/_authed/dashboard/transactions/new/_layout/'
      path: '/'
      fullPath: '/dashboard/transactions/new/'
      preLoaderRoute: typeof AuthedDashboardTransactionsNewLayoutIndexRouteImport
      parentRoute: typeof AuthedDashboardTransactionsNewLayoutRoute
    }
    '/_authed/dashboard/transactions/$transactionId/_layout/': {
      id: '/_authed/dashboard/transactions/$transactionId/_layout/'
      path: '/'
      fullPath: '/dashboard/transactions/$transactionId/'
      preLoaderRoute: typeof AuthedDashboardTransactionsTransactionIdLayoutIndexRouteImport
      parentRoute: typeof AuthedDashboardTransactionsTransactionIdLayoutRoute
    }
  }
}

interface AuthedDashboardConnectionsLayoutRouteChildren {
  AuthedDashboardConnectionsLayoutIndexRoute: typeof AuthedDashboardConnectionsLayoutIndexRoute
}

const AuthedDashboardConnectionsLayoutRouteChildren: AuthedDashboardConnectionsLayoutRouteChildren =
  {
    AuthedDashboardConnectionsLayoutIndexRoute:
      AuthedDashboardConnectionsLayoutIndexRoute,
  }

const AuthedDashboardConnectionsLayoutRouteWithChildren =
  AuthedDashboardConnectionsLayoutRoute._addFileChildren(
    AuthedDashboardConnectionsLayoutRouteChildren,
  )

interface AuthedDashboardTransactionsLayoutRouteChildren {
  AuthedDashboardTransactionsLayoutIndexRoute: typeof AuthedDashboardTransactionsLayoutIndexRoute
}

const AuthedDashboardTransactionsLayoutRouteChildren: AuthedDashboardTransactionsLayoutRouteChildren =
  {
    AuthedDashboardTransactionsLayoutIndexRoute:
      AuthedDashboardTransactionsLayoutIndexRoute,
  }

const AuthedDashboardTransactionsLayoutRouteWithChildren =
  AuthedDashboardTransactionsLayoutRoute._addFileChildren(
    AuthedDashboardTransactionsLayoutRouteChildren,
  )

interface AuthedDashboardTransactionsTransactionIdLayoutRouteChildren {
  AuthedDashboardTransactionsTransactionIdLayoutIndexRoute: typeof AuthedDashboardTransactionsTransactionIdLayoutIndexRoute
}

const AuthedDashboardTransactionsTransactionIdLayoutRouteChildren: AuthedDashboardTransactionsTransactionIdLayoutRouteChildren =
  {
    AuthedDashboardTransactionsTransactionIdLayoutIndexRoute:
      AuthedDashboardTransactionsTransactionIdLayoutIndexRoute,
  }

const AuthedDashboardTransactionsTransactionIdLayoutRouteWithChildren =
  AuthedDashboardTransactionsTransactionIdLayoutRoute._addFileChildren(
    AuthedDashboardTransactionsTransactionIdLayoutRouteChildren,
  )

interface AuthedDashboardTransactionsNewLayoutRouteChildren {
  AuthedDashboardTransactionsNewLayoutIndexRoute: typeof AuthedDashboardTransactionsNewLayoutIndexRoute
}

const AuthedDashboardTransactionsNewLayoutRouteChildren: AuthedDashboardTransactionsNewLayoutRouteChildren =
  {
    AuthedDashboardTransactionsNewLayoutIndexRoute:
      AuthedDashboardTransactionsNewLayoutIndexRoute,
  }

const AuthedDashboardTransactionsNewLayoutRouteWithChildren =
  AuthedDashboardTransactionsNewLayoutRoute._addFileChildren(
    AuthedDashboardTransactionsNewLayoutRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardConnectionsLayoutRoute: typeof AuthedDashboardConnectionsLayoutRouteWithChildren
  AuthedDashboardTransactionsLayoutRoute: typeof AuthedDashboardTransactionsLayoutRouteWithChildren
  AuthedDashboardTransactionsTransactionIdLayoutRoute: typeof AuthedDashboardTransactionsTransactionIdLayoutRouteWithChildren
  AuthedDashboardTransactionsNewLayoutRoute: typeof AuthedDashboardTransactionsNewLayoutRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardConnectionsLayoutRoute:
    AuthedDashboardConnectionsLayoutRouteWithChildren,
  AuthedDashboardTransactionsLayoutRoute:
    AuthedDashboardTransactionsLayoutRouteWithChildren,
  AuthedDashboardTransactionsTransactionIdLayoutRoute:
    AuthedDashboardTransactionsTransactionIdLayoutRouteWithChildren,
  AuthedDashboardTransactionsNewLayoutRoute:
    AuthedDashboardTransactionsNewLayoutRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiRecurringTransactionsIdRouteChildren {
  ApiRecurringTransactionsIdToggleRoute: typeof ApiRecurringTransactionsIdToggleRoute
}

const ApiRecurringTransactionsIdRouteChildren: ApiRecurringTransactionsIdRouteChildren =
  {
    ApiRecurringTransactionsIdToggleRoute:
      ApiRecurringTransactionsIdToggleRoute,
  }

const ApiRecurringTransactionsIdRouteWithChildren =
  ApiRecurringTransactionsIdRoute._addFileChildren(
    ApiRecurringTransactionsIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiConnectionsIdRoute: ApiConnectionsIdRoute,
  ApiRecurringTransactionsIdRoute: ApiRecurringTransactionsIdRouteWithChildren,
  ApiTransactionsIdRoute: ApiTransactionsIdRoute,
  ApiTransactionsYearsRangeRoute: ApiTransactionsYearsRangeRoute,
  ApiCashflowIndexRoute: ApiCashflowIndexRoute,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiConnectionsIndexRoute: ApiConnectionsIndexRoute,
  ApiRecurringTransactionsIndexRoute: ApiRecurringTransactionsIndexRoute,
  ApiTransactionsIndexRoute: ApiTransactionsIndexRoute,
  ApiConnectionsRequestsIndexRoute: ApiConnectionsRequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
